#!/usr/bin/env python3
"""Generate a deterministic Mandarin-English code-switch stress corpus with macOS TTS."""

import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path("/tmp/autobyteus-voice-backend-study-20260802")
OUTPUT = ROOT / "corpus/mixed-tts-v1"
SENTENCES = [
    "请打开 AutoByteus settings 然后选择 Luna Medium 模型。",
    "今天的 sprint review 安排在下午三点，请提前准备 demo。",
    "把这个 markdown file 保存到 local workspace 里面。",
    "我们需要检查 backend logs 才能找到 performance bottleneck。",
    "请使用 Codex runtime 运行这个 software engineering team。",
    "点击 architecture reviewer 发送的 reference file。",
    "这个 WebSocket stream 每秒发送很多 content delta events。",
    "我想比较 MLX Whisper 和 sherpa ONNX 的 latency。",
    "Mandarin Chinese output 应该统一转换成 simplified Chinese。",
    "请把 voice input language mode 设置成 auto detect。",
    "明天上午十点进行 API end to end testing。",
    "这个 pull request 需要 code review 和 regression tests。",
    "请记录 cold start warm inference 和 peak memory。",
    "Electron app 不应该在 renderer thread 里面运行模型。",
    "我们先优化 voice runtime 然后再修改 AutoByteus Web。",
    "这个 model package 的 SHA two five six 必须能够验证。",
    "用户说 start recording 以后应该立即显示 loading state。",
    "请不要使用 network fallback 所有 transcription 必须 local。",
    "SenseVoice Small 对 Chinese ASR 可能更快但需要测试 quality。",
    "Whisper Small 在 English speech 上通常保持很好的 accuracy。",
    "我们要测试 punctuation numbers proper nouns 和 mixed language。",
    "把 meeting notes 导出为 UTF eight encoded text file。",
    "如果 runtime handshake 失败就返回 stable error code。",
    "selected model identity 必须和 installed manifest 完全一致。",
    "请运行 thirty cold trials 和 one hundred warm trials。",
    "在 M one Max MacBook Pro 上测量 resident set size。",
    "这个 release candidate 不能在 architecture approval 以前发布。",
    "请把 transcript 插入当前 active text field 的 cursor position。",
    "今天我们测试 Wi Fi settings OpenAI API 和 local database。",
    "最终设计应该 evidence driven 而不是先假设 Node 或 Python。",
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest


def duration_ms(path: Path) -> int:
    output = subprocess.check_output(
        ["/opt/homebrew/bin/ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=nw=1:nk=1", str(path)],
        text=True,
    )
    return round(float(output.strip()) * 1000)


def main() -> int:
    audio = OUTPUT / "audio"
    audio.mkdir(parents=True, exist_ok=True)
    clips = []
    for index, sentence in enumerate(SENTENCES, start=1):
        clip_id = f"mixed-tts-{index:02d}"
        source = audio / f".{clip_id}.aiff"
        destination = audio / f"{clip_id}.wav"
        subprocess.run(["/usr/bin/say", "-v", "Tingting", "-o", str(source), sentence], check=True)
        subprocess.run(
            ["/opt/homebrew/bin/ffmpeg", "-nostdin", "-hide_banner", "-loglevel", "error", "-y", "-i", str(source), "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", str(destination)],
            check=True,
        )
        source.unlink()
        clips.append(
            {
                "id": clip_id,
                "category": "mixed",
                "languageMode": "auto",
                "path": f"audio/{destination.name}",
                "durationMs": duration_ms(destination),
                "speakerId": "macos-tingting-tts",
                "reference": sentence,
                "requiredTerms": [token for token in sentence.replace("。", "").split() if token.isascii()],
                "sha256": sha256(destination),
            }
        )
    corpus = {
        "schemaVersion": 1,
        "corpusId": "macos-tingting-mandarin-english-code-switch-v1",
        "version": "1",
        "license": {
            "licensedRealSpeech": False,
            "provenanceReference": "Locally generated by macOS Tingting TTS for mechanical code-switch stress testing.",
            "selectionLimitation": "Synthetic single-speaker audio is not authority for real-speaker absolute accuracy or product acceptance.",
        },
        "clips": clips,
    }
    manifest = OUTPUT / "corpus.json"
    manifest.write_text(json.dumps(corpus, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(manifest)
    print(f"clips={len(clips)} durationSeconds={sum(c['durationMs'] for c in clips) / 1000:.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
